# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0df168b988b2f3604df71c0aa324cdc6fc4b858d019957b7d33abde8889a00a1708cad48a1d857eba2b3f05e241971348244bffcaf1592791dffbe456fc24f1

test:
  secret_key_base: f39d255be092c6a57aae01b65446fbc1aefe0a69ffe634570315ef73596e910a8f39cf9e09ce880a21ab8d13b813693985bd52dccdad352b40dec3b25ba4c673

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  
